/**
 *      @file  callbacks.c
 *      @brief  Callbacks
 *
 * This file contains all callback functions wich interact with
 * GTK widgets.
 *
 *     @author  Miguel Gaspar, miguel.gaspar124@ua.pt
 *
 *   @internal
 *     Created  27-Sep-2017
 *     Company  University of Aveiro
 *   Copyright  Copyright (c) 2017, Miguel Gaspar
 *
 ***************************************************
 */
#include "myf.h"

/**
 * @brief  Function to process the text from some entrys and fills
 *    datasr structure used for shared memory. With this, the comunication
 *    manager will receive those parameters to send to the server.
 *    It also checks for blank entrys and sets them to -1 so the python script
 *    will interpret them and use default values.
 *
 * @param widget - the one that originated the call
 * @param user_data - Custom data with a widget ID to fetch some info
 * @return void.
 */
void on_simulation_clicked(GtkWidget *widget, GdkEvent * event ,gpointer user_data)
{
  /* Get GtkEntrys from their ID */
  GtkEntry *length_entry = GTK_ENTRY(gtk_builder_get_object(builderG,"length_entry"));
  GtkEntry *youngM_entry = GTK_ENTRY(gtk_builder_get_object(builderG,"youngM_entry"));
  GtkEntry *poisson_entry = GTK_ENTRY(gtk_builder_get_object(builderG,"poisson_entry"));
  GtkEntry *jobname_entry = GTK_ENTRY(gtk_builder_get_object(builderG,"jobname_entry"));
  if(length_entry && youngM_entry && poisson_entry && jobname_entry)
  {
          /* fetch all parameters needed for simulation from entrys */
          sprintf(data->length, "%s",gtk_entry_get_text(length_entry));
          sprintf(data->youngM, "%s",gtk_entry_get_text(youngM_entry));
          sprintf(data->poisson, "%s",gtk_entry_get_text(poisson_entry));
          sprintf(data->jobname, "%s",gtk_entry_get_text(jobname_entry));

          /* Check for blank entrys */
          if (!strcmp(data->length,"")) {
                  printf("length entry is empty, default value is going to be used\n");
                  sprintf(data->length,"-1"); // the python script
          }
          if (!strcmp(data->youngM,"")) {
                  printf("Young Module entry is empty, default value is going to be used\n");
                  sprintf(data->youngM,"-1");
          }
          if (!strcmp(data->poisson,"")) {
                  printf("Poisson entry is empty, default value is going to be used\n");
                  sprintf(data->poisson,"-1");
          }
          if (!strcmp(data->jobname,"")) {
                  printf("Job Name entry is empty, default name is going to be used\n");
                  sprintf(data->jobname,"default");
          }
          data->flag = 1;  // flag to send simulation parameters
  }
  else
  {
          printf("Could not get at least one entry from ID\n");
  }
}

/**
 * @brief  Callback Function to process events triggered by stress
 *      button. It will load from file an image generated by the simulation
 *      and display it on drawingarea1.
 *
 * @param widget - the one that originated the call
 * @param user_data - Custom data with a widget ID to fetch some info
 * @return void.
 */
void on_stress_clicked(GtkWidget *widget, GdkEvent * event ,gpointer user_data)
{
  GdkPixbuf *pix;
  GError *err = NULL;
  GError *err1 = NULL;
  cairo_t *cr;
  char filename[100];

  /* get GtkWidget drawingarea from drawingarea ID*/
  GtkWidget *drawingarea=GTK_WIDGET(gtk_builder_get_object (builderG, "drawingarea1"));
  /* cairo create */
  cr = gdk_cairo_create (gtk_widget_get_window(drawingarea));
  /* set background color to white cairo set source rgb */
  cairo_set_source_rgb(cr, 1, 1, 1);  //define color (rgb)
  cairo_paint(cr);      // paint on drawingarea1
  /* generate a filename from Job Name given by user input*/
  sprintf(filename,"%s_step-0_S_S11_Iso.png",data->jobname);
  /* Create pixbuf */
  pix = gdk_pixbuf_new_from_file(filename, &err); // get image
  // Error handling
  if(err)
  {
          printf("Error : %s\n", err->message);
          g_error_free(err);
          pix = gdk_pixbuf_new_from_file("../src/error.png", &err1); // get image
          PrintOnLog ("Simulation Failed\n");
  }
  /* set loaded image to cr */
  gdk_cairo_set_source_pixbuf(cr, pix, 0, 0);
  cairo_paint(cr);    // paint on drawingarea1
  cairo_paint(cr);    // paint again
  cairo_destroy (cr);
}


/**
 * @brief  Callback Function to process events triggered by displacement
 *      button. It will load from file an image generated by the simulation
 *      and display it on drawingarea1.
 *
 * @param widget - the one that originated the call
 * @param user_data - Custom data with a widget ID to fetch some info
 * @return void.
 */
void on_displacement_clicked(GtkWidget *widget, GdkEvent * event ,gpointer user_data)
{
  GdkPixbuf *pix;
  GError *err = NULL;
  GError *err1 = NULL;
  cairo_t *cr;
  char filename[100];

  /* get GtkWidget drawingarea from drawingarea ID*/
  GtkWidget *drawingarea=GTK_WIDGET(gtk_builder_get_object (builderG, "drawingarea1"));
  /* cairo create */
  cr = gdk_cairo_create (gtk_widget_get_window(drawingarea));
  /* set background color to white cairo set source rgb */
  cairo_set_source_rgb(cr, 1, 1, 1);  //define color (rgb)
  cairo_paint(cr);      // paint on drawingarea1
  /* generate a filename from Job Name given by user input*/
  sprintf(filename,"%s_step-0_U_U1_Iso.png",data->jobname);
  /* Create pixbuf */
  pix = gdk_pixbuf_new_from_file(filename, &err); // get image
  // Error handling
  if(err)
  {
          printf("Error : %s\n", err->message);
          g_error_free(err);
          pix = gdk_pixbuf_new_from_file("../src/error.png", &err1); // get image
          PrintOnLog ("Simulation Failed\n");
  }
  /* set loaded image to cr */
  gdk_cairo_set_source_pixbuf(cr, pix, 0, 0);
  cairo_paint(cr);    // paint on drawingarea1
  cairo_paint(cr);    // paint again
  cairo_destroy (cr);
}


/**
 * @brief  Callback Function to process events triggered by graph
 *      button. It will load from file an image generated by the simulation
 *      and display on drawingarea1.
 *
 * @param widget - the one that originated the call
 * @param user_data - Custom data with a widget ID to fetch some info
 * @return void.
 */
void on_graph_clicked(GtkWidget *widget, GdkEvent * event ,gpointer user_data)
{
  GdkPixbuf *pix;
  GError *err = NULL;
  GError *err1 = NULL;
  cairo_t *cr;
  GdkColor color;
  char filename[100];

  /* get GtkWidget drawingarea from drawingarea ID*/
  GtkWidget *drawingarea=GTK_WIDGET(gtk_builder_get_object (builderG, "drawingarea1"));
  /* cairo create */
  cr = gdk_cairo_create (gtk_widget_get_window(drawingarea));
  /* set background color to white with color structure*/
  cairo_set_source_rgb(cr, 1, 1, 1);  //define color (rgb)
  cairo_paint(cr);      // paint on drawingarea1
  /* generate a filename from Job Name given by user input*/
  sprintf(filename,"%s_Xplot_step-beamLoad_x-ALLSE.png",data->jobname);
    /* Create pixbuf */
  pix = gdk_pixbuf_new_from_file(filename, &err); // get image
  // Error handling
  if(err)
  {
          printf("Error : %s\n", err->message);
          g_error_free(err);
          pix = gdk_pixbuf_new_from_file("../src/error.png", &err1); // get image
          PrintOnLog ("Simulation Failed\n");
  }
  /* set loaded image to cr */
  gdk_cairo_set_source_pixbuf(cr, pix, 0, 0);
  cairo_paint(cr);    // paint on drawingarea1
  cairo_paint(cr);    // paint on drawingarea1
  cairo_destroy (cr);
}

/**
 * @brief  time out function to loop every second while return is TRUE.
 *      Every second checks if a simulation is submited or completed.
 *
 *
 * @param user_data - Custom data with a widget ID to fetch some info
 * @return TRUE
 */
gboolean my_timeout(gpointer user_data)
{
  PrintStatus(1);
  /*if flag is set, a simulation was submited */
  if (data->flag){
          data->flag = 0;   // set flag back to 0
          PrintOnLog("Simulation Running, please wait a moment\n");
  }
  /* if simstatus is set, simulation was complete*/
  if (data->simstatus){
          ChangeButtons(TRUE); // enable stress,displacement,graph buttons
          PrintOnLog("Simulation Completed!!\n");
          data->simstatus = 0; // set simstatus back to 0
  }
  return TRUE;     //continue running
}
